# Generated by Django 3.1.2 on 2021-05-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Done'),
        ),
    ]
